---
- name: Setup repo mirrors
  copy: src={{item.src}} dest={{item.dest}}
  notify: yum makecache
  with_items:
    - { src: 'RPM-GPG-KEY-EPEL-6', dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6' }  
    - { src: 'Centos-6.repo', dest: '/etc/yum.repos.d/CentOS-Base.repo' }  
    - { src: 'epel.repo', dest: '/etc/yum.repos.d/epel.repo' }  

- meta: flush_handlers

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Setup Iptables rules
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables
