---
- hosts: localhost
  connection: local
  gather_facts: 'no'
  roles: 
    - role: xiaopal.npc_setup
      npc_instances: 
        - name: 'tomcat-lb-server'
          present: false
        - name: 'tomcat-server-{1..2}'
          present: false
        - name: 'tomcat-memcached-{1..2}'
          present: false
