---
# Setup npc instances
- hosts: localhost
  gather_facts: 'no'
  tasks:
    - shell: "echo '# !/bin/bash' >mirror.sh"
    - with_dict: '{{mirror_images}}'
      args:
        executable: /bin/bash
      shell: echo '(SRC_IMAGE="{{item.value}}:{{mirror_tags[item.key]}}" &&
        DEST_IMAGE="hub.c.163.com/xiaopal/$SRC_IMAGE" &&
        docker pull "$SRC_IMAGE" && 
        docker tag "$SRC_IMAGE" "$DEST_IMAGE" &&
        docker push "$DEST_IMAGE")&' >>mirror.sh
  vars:
    kube_version: v1.6.7
    etcd_version: v3.0.17
    weave_version: '2.0.1'
    flannel_version: v0.6.2
    pod_infra_version: '3.0'
    netcheck_version: "v1.0"
    fluentd_version: "1.22"
    kibana_version: "v4.6.1"
    helm_version: "v2.2.2"
    tiller_version: "{{ helm_version }}"
    kubedns_version: '1.14.2'
    kubednsautoscaler_version: '1.1.1'
    elasticsearch_version: "v2.4.1"

    mirror_images:
      etcd_image: "quay.io/coreos/etcd"
      flannel_image: "quay.io/coreos/flannel"
      calico_rr_image: "quay.io/calico/routereflector"
      pod_infra_image: "gcr.io/google_containers/pause-amd64"
      netcheck_agent: "quay.io/l23network/k8s-netchecker-agent"
      kubedns_image: "gcr.io/google_containers/k8s-dns-kube-dns-amd64"
      dnsmasq_nanny_image: "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64"
      dnsmasq_sidecar_image: "gcr.io/google_containers/k8s-dns-sidecar-amd64"
      hyperkube_image: "quay.io/coreos/hyperkube"
      netcheck_server: "quay.io/l23network/k8s-netchecker-server"
      kubednsautoscaler_image: "gcr.io/google_containers/cluster-proportional-autoscaler-amd64"
      elasticsearch_image: "gcr.io/google_containers/elasticsearch"
      fluentd_image: "gcr.io/google_containers/fluentd-elasticsearch"
      kibana_image: "gcr.io/google_containers/kibana"
      tiller_image: "gcr.io/kubernetes-helm/tiller"
    mirror_tags:
      etcd_image: "{{ etcd_version }}"
      flannel_image: "{{ flannel_version }}"
      calico_rr_image: "v0.3.0"
      hyperkube_image: "{{ kube_version }}_coreos.0"
      pod_infra_image: "{{ pod_infra_version }}"
      netcheck_agent: "{{ netcheck_version }}"
      netcheck_server: "{{ netcheck_version }}"
      kubedns_image: "{{ kubedns_version }}"
      dnsmasq_nanny_image: "{{ kubedns_version }}"
      dnsmasq_sidecar_image: "{{ kubedns_version }}"
      kubednsautoscaler_image: "{{ kubednsautoscaler_version }}"
      elasticsearch_image: "{{ elasticsearch_version }}"
      fluentd_image: "{{ fluentd_version }}"
      kibana_image: "{{ kibana_version }}"
      tiller_image: "{{ tiller_version }}"
